language: node_js
node_js: stable

addons:
  apt:
    update: true

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - git submodule update --remote --merge

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Denley Hsiao"
  - git config user.email "denley@justtodo.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_REPO}" master:master

branches:
  only:
    - blog

env:
  global:
    - GITHUB_REPO: github.com/denleyhsiao/denleyhsiao.github.io.git
    - secure: CdJyYn/4AImCApwTz/xTMdcY+OKvv9qkzaBoq4x2qIfa452bKu7TiMudVp9FrMmT5F5pUQ8np3EhCRZ+JpeFr4R44Mm5kcu/hvc9neilDV8V+AX0GaPV/ntbMLTJMTnH3XycH/bhKEYxJX70/q6oqaMEEI9wcO2isEg2XGp2mJu9i7de+6trgRjpfcXazMbOdwXHrhM/k3R4kCyVecDyzgcEroumuC1JGGpzOn4SLml8Xuk9l7wlTdkfKtoV9NbSK3/9oRsxcmtsQTai6/zlce121qlAXXyFGR47OSpHmKbk0dbDdhw9oAhUSdPOAwvAE13pA0Vtjn97OWVcdfjsSYyA8TCh/SE6GS+nHYD09SkzaJWNWRtfZyaefvHXvTVTx/EBdsXgOM45zeopnYYOLumgEt0jWMEDbPx41i7v4iT9ErfQ77xTWYPDW47HrPKrYp7DzfESzD8kpRHci0X8u0bcjS6kv0gD3XyktV9sEdeYHavMzahYLrJgJuz8FlmjgvDUM2/CMKFQ2tVNwYutbF+y9o3h3LvKEIYFjRx9WJBo2QQtDb8DymzftKyd/eue6W45nxwQ/QW1dn9/R6omOGjCcStvr6/ZcErGrTXjRgYPrFkJJSYvG0BMl+V5+GpO1j/+71svAHaBJaF+z83Jad8TUdT/gK3vaKEPp1b4EyE=